name: project2
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  cloud_firestore: ^4.7.0
  firebase_auth: ^4.2.9
  firebase_storage: ^11.2.0
  google_sign_in: ^6.0.1
  sign_in_button: ^3.0.0
  image_picker: ^0.8.7+1
  geolocator: ^9.0.2
  lottie: ^2.3.1
  firebase_phone_auth_handler: ^1.0.8
  fluttertoast: ^8.2.1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  geocoding: ^2.1.0
  cool_alert: ^2.0.1
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.2.16
  location: ^4.4.0
  permission_handler: ^10.3.0
  android_intent_plus: ^4.0.1
  sizer: ^2.0.15




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: images/splash2.png
  android: true
  ios: true
  android_12:
    image: images/splash2.png
    android: true

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

